# Site settings
title: "Tidy Fox Development"
email: awynter@tidyfoxdev.com
description: > # this means to ignore newlines until "baseurl:"
 When you need tidy web software solutions to complex web problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tidyfoxdev.com" # the base hostname & protocol for your site
twitter_username: awochna
github_username: awochna
collections:
  projects:
    output: true
    permalink: "/projects/:path/"

gems: ['jekyll-paginate']

# Build settings
markdown: kramdown
lsi: true
exclude: ['Gemfile', 'Gemfile.lock', '.DS_Store']
paginate: 5
paginate_path: "/blog/page/:num"

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      author: "Alex Wynter"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alex Wynter"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Alex Wynter"
