# Site settings
title: awochna.com
email: awochna@awochna.com
description: > # this means to ignore newlines until "baseurl:"
 Blog of a (rails|drupal|sass|ember|...|nerd). 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://awochna.com" # the base hostname & protocol for your site
twitter_username: awochna
github_username: awochna
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Build settings
markdown: kramdown
lsi: true

defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      author: "Alex Wochna"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alex Wochna"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      author: "Alex Wochna"
